version: '3.9'
# inspired from https://www.bornfight.com/blog/blog-lamp-docker-setup-with-php-8-and-mariadb-for-symfony-projects/
# and https://mariadb.com/kb/en/setting-up-a-lamp-stack-with-docker-compose/
services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: 10.10.0.1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: capstone
      MYSQL_USER: capstone
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      network:
        ipv4_address: 10.10.10.1
    healthcheck:
      test: ["CMD-SHELL", "mysql capstone -ucapstone -p${MYSQL_PASSWORD} -e 'SELECT 1;'  || exit 1"]
      interval: 2s
      retries: 120

  admin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - '${ADMIN_PORT}:80'
    environment:
      PMA_HOST: mariadb
    volumes:
      - admin_data:/var/www/html
    networks:
      - network
    depends_on:
      mariadb:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${APP_PORT}:80'
    environment:
      - 'DATABASE_URL=mysql://capstone:${MYSQL_PASSWORD}@mariadb:3306/capstone'
    volumes:
      - ./site.conf:/etc/apache2/sites-enabled/site.conf
      - ./:/var/www/capstone-ss23
      - ./mail.txt:/var/www/web-log/email-log.txt
    networks:
      - network
    depends_on:
      mariadb:
        condition: service_healthy
      admin:
        condition: service_started

volumes:
  mariadb_data:
  admin_data:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
